name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ "main" ]

jobs:
  build-windows:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: windows-2025-vs2026
    env:
      VCPKG_ENABLE_METRICS: 0
      VCPKG_DEFAULT_BINARY_CACHE: ~/.cache/vcpkg/archives
    steps:
      - uses: actions/checkout@v6

      - name: Setup NSIS
        uses: repolevedavaj/install-nsis@v1.1.0
        with:
          nsis-version: '3.11'

      - name: Restore vcpkg binary cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/vcpkg/archives
          key: vcpkg-binary-${{ runner.os }}-${{ matrix.triplet }}
          restore-keys: |
            vcpkg-binary-${{ runner.os }}-${{ matrix.triplet }}-

      - name: Restore installed packages
        uses: actions/cache/restore@v4
        with:
          path: build/vcpkg_installed
          key: vcpkg-installed-${{ runner.os }}-${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-installed-${{ runner.os }}-${{ matrix.triplet }}-

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Run CMake
        uses: lukka/run-cmake@v10
        env:
          VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
          VCPKG_DEFAULT_TRIPLET: 'x64-windows-release'
        with:
          configurePreset: 'ci-vcpkg-release'
          buildPreset: 'ci-vcpkg-build'
          packagePreset: 'ci-vcpkg-package'

      - name: Save vcpkg binary cache
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/vcpkg/archives
          key: vcpkg-binary-${{ runner.os }}-${{ matrix.triplet }}

      - name: Save installed packages
        uses: actions/cache/save@v4
        with:
          path: build/vcpkg_installed
          key: vcpkg-installed-${{ runner.os }}-${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}

      - name: Upload installer artifact
        uses: actions/upload-artifact@v6
        with:
          name: Jakki-Windows-Installer
          path: package/*.exe
