name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-2025-vs2026
    env:
      VCPKG_ENABLE_METRICS: 0
    steps:
      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-vcpkg-release'
          buildPreset: 'ci-vcpkg-release'
          packagePreset: 'ci-vcpkg-release'
